services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sleep", "infinity"]
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://user:pass@db:5432/moyklass_task"
    volumes:
      - ..:/workspace:cached
  db:
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "moyklass_task"
    image: postgres
